---
version: "3"
services:
  helix-p4d-server:
    # Use the dockerfile in the source folder
    build: ./source
    container_name: helix-p4d-server
    # Map the perforce root folder to something on this local machine
    # Set in the .env file, the default is ./root
    volumes:
      - ${P4_Local_Root}:${P4ROOT}
    restart: unless-stopped
    # Expose the p4 port with the option to change the host port via env
    ports:
     - ${External_P4_Port}:${P4PORT}
    # We have to copy over the env vars set in the .env file to the dockerfile
    environment:
      - P4PORT=${P4PORT}
      - P4ROOT=${P4ROOT}
      - P4USER=${P4USER}
      - P4PASSWD=${P4PASSWD}